services:
  cafeteria:
    build: .
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cafeteria.rule=Host(`cafeteria.jcool-laboratory-00.click`)"
      - "traefik.http.routers.cafeteria.entrypoints=web"
      - "traefik.http.services.cafeteria.loadbalancer.server.port=4321"

networks:
  traefik:
    external: true
